name: MelonHigh
author: roblikescake
main: com.melonquest.roblikescake.melonhigh.MelonHigh
description: Wanna get high?
version: ${project.version}

permissions:
    melonhigh.admin:
        description: Players with this permission are exempt from Join/Quit/Kick Messages